### ISSUE TITLE
Synchronization issues with Tags

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-electron#2454]
Renaming a tag from iOS results in a blank tag showing inside a note in the web app.
Trying to do something with this tag later in the web app results in tags duplication and synchronization issues.

Please take a look at the following video:
[Tags.mov.zip](https://github.com/Automattic/simplenote-electron/files/5501332/Tags.mov.zip)

### Expected
Tags look and order is the same on all devices.

### Observed
* Tags are in a different order
* Renaming a tag on iOS results in an empty tag on the web
* Duplicated tags
* Invincible tags that can't be deleted

### Reproduced
0. Open the web app and iOS app
1. On the web: add tags `t1`, `t2`, `t3`, `t4` to the note
2. See that the order of tags is different
3. iOS: Rename `t2` to `t2-1`
4. Web: Tag `t2` in the note becomes empty
5. Web: Rename tag `t2-1` to `t2-1-1`
6. Web: There are now 2 tags `t2-1-1`

### Where did you see the bug
- System Make: Apple
- System Model: Macbook
- OS: Catalina
- OS version: 10.15.7
- Browser (if applicable): Safari
- Browser version (if applicable):  14
- Simplenote app version:

**Comment by codebykat** [comment]
@belcherj was this fixed by https://github.com/Automattic/simplenote-electron/pull/2455 or is that a separate issue?

**Comment by belcherj** [comment]
This is still an issue. We have different encoding on different platforms and when the encoding is different we run into issues.

**Comment by belcherj** [comment]
- Add the tag "a" to a note in electron or ios.
- On iOS edit the tag in the tag list to "a-1".
- On web notice that it is blank

<img width="92" alt="Screen Shot 2020-11-24 at 2 17 09 PM" src="https://user-images.githubusercontent.com/6817400/100141084-d7123e80-2e5f-11eb-8226-498c0b60804a.png">

This is because ios hashes differently than Android and Web

**Comment by reginabally** [comment]
There's a user report in 3642690-zen with a video recording.

**Comment by sandymcfadden** [comment]
I ran into something similar today in two different scenarios where it ended up with a blank tag on a note and the tag not showing in the tag list.

Scenario 1
- Add new tag from Web
- Delete tag from Web
- Add the same tag back from Electron
- Notice blank tag on web and not showing in tag list on web.

Scenario 2
- Add new tag from Web
- Delete tag from MacOS/iOS
- Add tag again from Web
- Notice tag does not show on MacOS/iOS


https://user-images.githubusercontent.com/1326294/106289665-edea5e00-621f-11eb-8ece-077eebf31d93.mov

**Comment by fluiddot** [comment]
I bumped into this issue too while I was working in adding the tags to the history screen. In my case, I managed to reproduce the Scenario 1 from the [previous comment](https://github.com/Automattic/simplenote-electron/issues/2454#issuecomment-769851063).

As far as I investigated, this problem could be related to the flow when a remove operation is sent while having multiple clients connected to the web socket.

In the following logs, you can see the messages I captured from the web socket connections of both clients when deleting the tag `tag-6`:

### Web client messages
#### Channel 1 - Tag bucket

Message sent:
```
{
    "o": "-",
    "id": "tag-6",
    "ccid": "<MESSAGE_CID_1>"
}
```

Message received:
```
[
    {
        "clientid": "<CLIENT_ID_WEB>",
        "id": "tag-6",
        "o": "-",
        "ev": 2,
        "cv": "<CV_1>",
        "ccids": ["<MESSAGE_CID_1>"]
    }
]
```

### Electron client messages
#### Channel 1 - Tag bucket
Message received:
```
[
    {
        "clientid": "<CLIENT_ID_WEB>", 
        "id": "tag-6", 
        "o": "-", 
        "ev": 2, 
        "cv": "<CV_1>", 
        "ccids": ["<MESSAGE_CID_1>"]
    }
]
```

Message sent: **[the tag was already removed so probably we shouldn't send this message]**
```
{
    "o":"-",
    "id":"tag-6",
    "ccid":"<MESSAGE_CID_2>"
}
```

Message received: **[Simperium responds with a `404` because the tag was already removed]**
```
[
    {
        "ccids": ["<MESSAGE_CID_2>"], 
        "id": "tag-6", 
        "clientid": "<CLIENT_ID_ELECTRON>", 
        "error": 404
    }
]
```

As you can see, when the remove operation is received in the Electron client, it tries to send another message with a remove operation for the same tag and receives an error because it was already removed.

I haven't checked further but my impression is that the error message is not handled properly because I noticed that the message is not removed from the channel's local queue after this. Most likely this leads to blocking any message for that tag because it keeps waiting for the previous message to be sent. So when the same tag is created in the Electron client, the update message is not being sent to Simperium. However the client sends the note update message that includes the tag, producing on the Web client the error mentioned in this issue about having an empty tag.

<img width="92" alt="Screen Shot 2020-11-24 at 2 17 09 PM" src="https://user-images.githubusercontent.com/6817400/100141084-d7123e80-2e5f-11eb-8226-498c0b60804a.png">
